version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t asrob/ubuntu-mariadb:10.3.8 .
      - run: docker push asrob/ubuntu-mariadb:10.3.8
